name: Deploy to Production
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --legacy-peer-deps
      - name: Make env file and add secrets to it
        run: |
          touch .env
          echo "NODE_ENV=production" >> .env
          echo "REACT_APP_BASE_URL=${{secrets.BACKEND_URL}}" >> .env
          echo "REACT_APP_GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
      - name: Build
        run: CI=false npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build