name: Deploy to Production
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --legacy-peer-deps
      - name: Make env file and add secrets to it
        run: |
          touch .env
          echo "NODE_ENV=production" >> .env
          echo "REACT_APP_BASE_URL=${{secrets.BACKEND_URL}}" >> .env
          echo "REACT_APP_GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
      - name: Build
        run: CI=false npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: List
        run: ls -a

      - name: Add SSH Key To Runner
        run: |
          mkdir ~/.ssh
          echo "${{secrets.REIMBURSEMENT_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Remove previous build
        run: ssh -o StrictHostKeyChecking=no reimbursement@${{secrets.FRONTEND_INSTANCE_IP}} "rm -rf reimbursement-fe"

      - name: Deploy production build
        run: scp -o StrictHostKeyChecking=no -r build reimbursement@${{secrets.FRONTEND_INSTANCE_IP}}:/home/reimbursement/reimbursement-fe
