name: Reimbursement Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: See directory
        run: ls
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: See directory
        run: ls

  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v1
        with:
          name: build

      - name: Add SSH Key To Runner
        run: |
          mkdir ~/.ssh
          echo "${{secrets.SSH_PRIVATE}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Remove previous build
        run: ssh -o StrictHostKeyChecking=no reimbursement@${{secrets.REMOTE_INSTANCE_IP}} "rm -rf reimbursement-frontend"

      - name: Deploy production build
        run: scp -o StrictHostKeyChecking=no -r build reimbursement@${{secrets.REMOTE_INSTANCE_IP}}:/home/reimbursement/reimbursement-frontend