name: Reimbursement Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - uses: actions/upload-artifact@v3
        with:
          name: prod-build
          path: ./
      - name: See directory
        run: ls

  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v1
        with:
          name: prod-build
          path: .
      - name: See directory
        run: ls
      - name: Add SSH Key To Runner
        env:
          SSH_PUBLIC: ${{secrets.SSH_PUBLIC}}
          SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
        run: |
          mkdir ~/.ssh
          echo $SSH_PUBLIC > ~/.ssh/id_rsa.pub
          echo "${{secrets.SSH_PRIVATE}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy production build
        run: scp -o StrictHostKeyChecking=no build sanjay@34.93.91.239:/home/sanjay/reimbursement-frontend